name: golocal_app
description: "GoLocal - Discover India's hidden heartbeat with authentic artisans, food, events, and guides."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^16.2.4
  
  # Backend & Database
  supabase_flutter: ^2.0.0
  
  # Storage & Cache
  shared_preferences: ^2.2.2
  
  # Networking
  http: ^1.1.2
  dio: ^5.4.0
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.2.1
  flutter_dotenv: ^5.1.0
  
  # Image Handling
  image_picker: ^1.0.4
  
  # Location Services
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.5.0
  google_places_flutter: ^2.0.9
  
  # Animations
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env
